apiVersion: v1
kind: Service
metadata:
  name: ws-app
spec:
  selector:
    app: ws-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: tcp
      port: 9999
      targetPort: 9999
